### ISSUE TITLE
Support for Riden RD6024?

### ISSUE THREAD

**Issue by Paul-Simpson** [tjko/riden-flashtool#10]
Hi,

Thanks for sharing this repo. I see that there's a version for each of the PSU's, but not the '24 model. Is this needed, and if so, can you provide it?

Cheers, Paul

**Comment by tjko** [comment]
Unfortunately, I don't have that PSU, so I can't really test if it would work.

If you try running _flash-rd.py_ without specifying firmware file, will it successfully detect your PSU model and firmware version?

**Comment by cygeus** [comment]
Here you go

> % ./flash-rd.py /dev/cu.usbserial-1440 
> Serial port: /dev/cu.usbserial-1440 (115200bps)
> Check if device is in bootloader mode...No
> Found a device (using Modbus): RD6024 (60241) v1.38
> Rebooting into bootloader mode...
> Device information (from bootloader):
>     Model: RD6024 (60241)
>  Firmware: v1.38
>       S/N: 00012551
> Unsupported device: 60241`

This has been tested using a RD6024 running

> RD6024 Bootloader V1.13
> Firmware Version:V1.38

I did add `60241` to `supported_models` and was able to successfully write an official firmware from [ruidengkeji](http://www.ruidengkeji.com/rdupdate/firmware/RD60241/) to my RD6024.

**Comment by tjko** [comment]
Thanks for testing.  I checked in change to add support for this model (e5803b5b341ed992c670bc5d7d123a46d6f33e4c).
