### ISSUE TITLE
RK6006-BT

### ISSUE THREAD

**Issue by grymoire** [tjko/riden-flashtool#16]
I have the bluetooth model - RK6006-BT
I uploaded the firmware from http://www.ruidengkeji.com/rdupdate/firmware/RK60066/

I added model RD60066  to the code as one of the allowed models and it worked.
Bootloader 1.04
Firmware 1.09

**Comment by tjko** [comment]
Thanks!  Just to confirm the model number you added to ```supported_models``` was 60066?

**Comment by grymoire** [comment]
Yes, the RK6006-BT has the model number 60066. 
The firmware is available on http://www.ruidengkeji.com/rdupdate/firmware/RK60066/ 
When I use your flasher, the screen reports:
```
RK6006 Bootloader V1.04
Firmware Version V1.09
```
When I use the python library RD6006, it reports the model as "Model : 6006.6"

**Comment by tjko** [comment]
Thanks!    Support for RK6006-BT added (a02a38cd7a5f69000ccc46e32645baea458e238d).
